version: '3.8'

services:
  app:
    build: ./app
    container_name: app
    ports:
      - "5555:5555"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./.certs:/etc/ssl:ro
    restart: always