version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=api.py
      - FLASK_ENV=production
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - flask-app
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./.certs:/etc/ssl:ro
    restart: always