version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-app
    expose:
      - "5000"
    environment:
      - FLASK_APP=api.py
      - FLASK_ENV=production
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - flask-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    restart: always

  certbot:
    build: ./certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx/:/etc/nginx/:rw
    entrypoint: "/bin/sh -c '/certbot.sh'"